services:
  postgres:
    image: postgres:14-alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_USER: pethelp
      POSTGRES_PASSWORD: veryComplexPassword
      POSTGRES_DB: pethelp
      DATADIR: /var/lib/postgresql/data/pgdata
      TZ: UTC
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'pethelp']
      interval: 5s
      timeout: 60s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "complexPassWord10"
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 60s
      retries: 5
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
  redis-data: