CREATE TABLE IF NOT EXISTS fees (
    id INTEGER PRIMARY KEY,
    order_id INTEGER NOT NULL,
    amount DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fees_order
        FOREIGN KEY (order_id) REFERENCES orders(id)
);