CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO specialists (
    id,
    name, 
    family_name, 
    email, 
    password_hash, 
    phone, 
    bio, 
    avatar,
    address_id,
    organisation_id,
    branch_id,
    position,
    experience, 
    description, 
    image_id,
    is_banned, 
    is_deleted, 
    is_active, 
    is_verified
)
VALUES
  (2,
    E'Ірина',
    E'Савчук',
    'iryna.savchuk@example.com',
    crypt('sobaky2024', gen_salt('bf')),
    '+380679998877',
    E'Мене звати Ірина, я професійна догсіттерка з 4-річним досвідом. Люблю собак з дитинства, і для мене це не просто робота — це стиль життя. Займаюсь вигулом, перетримкою та грумінгом. Працюю тільки з маленькими та середніми породами.', 
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/iryna-savchuk.png',
    (SELECT id FROM addresses WHERE street = 'вул. Тростянецька'),
    NULL,
    NULL,
    'Догсіттер',
    3,
    E'Турбота про вашого песика — моя місія!',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (3,
    E'Максим',
    E'Ковальчук',
    'maksym.kovalchuk@example.com',
    crypt('dogcat2024', gen_salt('bf')),
    '+380671234567',
    E'Я Максим — універсальний спеціаліст з догляду за домашніми улюбленцями. Працюю як з котами, так і з собаками. Маю досвід у грумінгу, вигулі та догляді вдома. Гарантую турботу, безпеку та комфорт для вашого улюбленця.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/maksym-kovalchuk.png',
    (SELECT id FROM addresses WHERE street = 'вул. Лаврська'),
    NULL,
    NULL,
    'Спеціаліст з догляду за тваринами',
    4,
    E'Професійний догляд для котів і собак — в одному місці.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (4,
    E'Тетяна',
    E'Мельник',
    'tetiana.melnyk@example.com',
    crypt('meowmeow2024', gen_salt('bf')),
    '+380503334455',
    E'Мене звати Тетяна. Я надаю індивідуальний догляд за котами у звичному для них середовищі — без перевезень, без стресу. Переїжджаю до вашої оселі на час вашої відсутності й піклуюся про хвостика, як про власного.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/tetiana-melnyk.png',
    (SELECT id FROM addresses WHERE street = 'просп. Оболонський'),
    NULL,
    NULL,
    'Котсіттер',
    5,
    E'Ваш кіт навіть не помітить, що вас немає вдома — бо я вже тут.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (5,
    E'Артем',
    E'Лисенко',
    'artem.lysenko@example.com',
    crypt('walkmydog', gen_salt('bf')),
    '+380683221145',
    E'Я студент КПІ, і у вільний час допомагаю вигулювати собак. Маю досвід з активними породами — люблю довгі прогулянки, і завжди приношу воду та ласощі для хвостиків. Працюю лише по вихідних.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/artem-lysenko.png',
    (SELECT id FROM addresses WHERE street = 'вул. Бориса Гмирі'),
    NULL,
    NULL,
    'Догвокер',
    6,
    E'Субота і неділя — ідеальний час для щасливих лап.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (6,
    E'Ольга',
    E'Демчук',
    'olha.demchuk@example.com',
    crypt('littlefriends2024', gen_salt('bf')),
    '+380663876543',
    E'Я Ольга, обожнюю маленьких песиків — у мене самої йорк. Приймаю тільки маленькі породи у себе вдома.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/olha-demchuk.png',
    (SELECT id FROM addresses WHERE street = 'вул. Євгена Коновальця'),
    NULL,
    NULL,
    'Догсіттер',
    7,
    E'Затишний собачий готель для малюків.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (7,
    E'Валерія',
    E'Черниш',
    'valeriia.chernysh@example.com',
    crypt('kittycomfort2024', gen_salt('bf')),
    '+380672205577',
    E'Я працюю графічною дизайнеркою й обожнюю проводити час з котами. Якщо вам потрібно, щоб хтось залишився з мурчиком вдома — я з радістю допоможу. Без стресу, без кліток, просто звичне життя вашої тваринки з новою подругою.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/valeriia-chernysh.png',
    (SELECT id FROM addresses WHERE street = 'вул. Бастіонна'),
    NULL,
    NULL,
    'Котсіттер',
    8,
    E'Я — спокійна компанія для вашого кота, поки ви у відїзді.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (8,
    E'Юлія',
    E'Сосновська',
    'yuliia.sosnovska@example.com',
    crypt('purrstyle2024', gen_salt('bf')),
    '+380662221100',
    E'Я Юлія, маю понад 6 років досвіду у грумінгу саме котів. Працюю вдома, маю професійне обладнання та спеціальні шампуні для різних типів шерсті.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/yuliia-sosnovska.png',
    (SELECT id FROM addresses WHERE street = 'вул. Златоустівська'),
    NULL,
    NULL,
    'Грумер',
    9,
    E'Чистий, пухнастий і щасливий — саме таким буде ваш кіт після візиту.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (9,
    E'Богдан',
    E'Соловей',
    'bohdan.solovey@example.com',
    crypt('staywithme2024', gen_salt('bf')),
    '+380993344556',
    E'Я студент та великий фанат тварин. Живу сам у двокімнатній квартирі, тому можу взяти улюбленця на перетримку на кілька днів. Маю досвід з доглядом за спокійними котами та невеликими собаками.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/bohdan-solovey.png',
    (SELECT id FROM addresses WHERE street = 'вул. Бальзака'),
    NULL,
    NULL,
    'Сіттер',
    10,
    E'Поки ви у відїзді — ваш улюбленець зі мною під наглядом.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (10,
    E'Катерина',
    E'Нечипоренко',
    'kateryna.nechyporenko@example.com',
    crypt('catsncare24', gen_salt('bf')),
    '+380674562398',
    E'Я Наталія, маю затишну квартиру без інших тварин і дітей, що ідеально підходить для чутливих котиків. Забезпечую спокійну атмосферу, дотримуюсь режиму харчування та надаю відео-звіти щодня.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/kateryna-nechyporenko.png',
    (SELECT id FROM addresses WHERE street = 'вул. Березняківська'),
    NULL,
    NULL,
    'Котсіттер',
    11,
    E'Ідеальне місце для вашого вибагливого котика.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (11,
    E'Юрій',
    E'Панасенко',
    'yurii.panasenko@example.com',
    crypt('dogwalker2024', gen_salt('bf')),
    '+380932222441',
    E'Привіт! Я Юрій, вигулюю собак у будні дні з 7:00 до 12:00. Працюю у районі Березняків, добре знаю всі вигульні майданчики. Пропоную як короткі, так і довгі прогулянки — за потребою.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/yurii-panasenko.png',
    (SELECT id FROM addresses WHERE street = 'вул. Лесі Українки'),
    NULL,
    NULL,
    'Догвокер',
    12,
    E'Ваш пес не сумуватиме, поки ви на роботі ☀️',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (12,
    E'Оксана',
    E'Мельничук',
    'oksana.melnychuk@example.com',
    crypt('homecarecats24', gen_salt('bf')),
    '+380667775544',
    E'Привіт! Я Оксана. Якщо ви у відрядженні чи відпустці — я подбаю про вашого котика у його звичному середовищі. Переїжджаю до квартири на час вашої відсутності, дотримуюсь усіх інструкцій, і щодня надсилаю фото.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/oksana-melnychuk.png',
    (SELECT id FROM addresses WHERE street = 'вул. Йорданська'),
    NULL,
    NULL,
    'Котсіттер',
    13,
    E'Ваш кіт вдома, а я — поруч з ним. Спокій для вас і муркотіння для нього.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (13,
    E'Інна',
    E'Шевченко',
    'inna.shevchenko@example.com',
    crypt('calmcat24', gen_salt('bf')),
    '+380973301122',
    E'Я Інна — мама маленької дитини і велика любителька котів. Приймаю тільки котів на перетримку у своїй світлій квартирі. У мене спокійно, чисто і без інших тварин, тому ваш мурчик почуватиметься як вдома.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/inna-shevchenko.png',
    (SELECT id FROM addresses WHERE street = 'вул. Серафимовича'),
    NULL,
    NULL,
    'Котсіттер',
    14,
    E'Тиха гавань для вашого пухнастика.',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (14,
    E'Андрій',
    E'Рубан',
    'andrii.ruban@example.com',
    crypt('groomingpro24', gen_salt('bf')),
    '+380503987654',
    E'Я Андрій, мобільний грумер. Приїжджаю до вас додому зі своїм обладнанням, щоб зробити вашу собаку чистою, охайною та щасливою. Мию, стрижу, підрізаю кігті — усе швидко, якісно і без стресу для песика.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/andrii-ruban.png',
    (SELECT id FROM addresses WHERE street = 'вул. Княжий Затон'),
    NULL,
    NULL,
    'Грумер',
    15,
    E'Салон краси для вашого собаки — просто у вас вдома',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  ),
  (15,
    E'Світлана',
    E'Андрущенко',
    'svitlana.andrushchenko@example.com',
    crypt('walkies2024', gen_salt('bf')),
    '+380673332211',
    E'Привіт! Мене звати Світлана. Щодня вигулюю собак у Дарницькому районі — добре знаю, де безпечно і цікаво. Маю досвід з собаками різного характеру — від активних до обережних. Завжди на звязку з господарем.',
    'https://jjniaoujdyanpybytgnq.supabase.co/storage/v1/object/sign/avatars/svitlana-andrushchenko.png',
    (SELECT id FROM addresses WHERE street = 'вул. Якуба Коласа'),
    NULL,
    NULL,
    'Догвокер',
    16,
    E'Турбота, контроль і радість — ось як проходить наша прогулянка',
    ARRAY[]::TEXT[],
    false,
    false,
    true,
    true
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO specialist_services (
    specialist_id,
    service_id
) VALUES 
    (2, 1),
    (2, 4),
    (2, 2),
    (3, 1),
    (3, 4),
    (3, 6),
    (3, 7),
    (4, 6),
    (5, 1),
    (6, 2),
    (7, 6),
    (8, 1),
    (9, 5),
    (9, 2),
    (10, 1),
    (10, 4),
    (11, 2),
    (12, 1),
    (13, 7),
    (13, 4),
    (14, 7),
    (15, 1)
ON CONFLICT (specialist_id, service_id) DO NOTHING;
