name: CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/pethelpdev/teammarket-pethelp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Amazon Lightsail via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.AMAZON_SERVER_USERNAME }}
          key: ${{ secrets.AMAZON_SERVER_SSH }}
          script: |
            REGISTRY="docker.io"
            IMAGE_NAME="pethelpdev/teammarket-pethelp"
            TAG_NAME="latest"
            FULL_IMAGE_NAME="$REGISTRY/$IMAGE_NAME:$TAG_NAME"

            echo "Deploying: $FULL_IMAGE_NAME"
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            sudo docker pull "$FULL_IMAGE_NAME" || { echo "Pull failed!"; exit 1; }

            if sudo docker ps -q -f name=pethelp-backend >/dev/null; then
              sudo docker stop pethelp-backend
              sudo docker rm pethelp-backend
            fi

            sudo docker run -d -p 8080:8080 --name pethelp-backend "$FULL_IMAGE_NAME"
            sudo docker image prune -f
